# Generated by Django 2.1.3 on 2018-11-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='browser_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_filters', models.CharField(max_length=999)),
                ('no_filter', models.CharField(max_length=999)),
                ('price', models.CharField(max_length=999)),
                ('low_to_high', models.CharField(max_length=999)),
                ('high_to_low', models.CharField(max_length=999)),
                ('name', models.CharField(max_length=999)),
                ('a_to_z', models.CharField(max_length=999)),
                ('z_to_a', models.CharField(max_length=999)),
                ('okidoki', models.CharField(max_length=999)),
                ('osta', models.CharField(max_length=999)),
                ('soov', models.CharField(max_length=999)),
                ('kuldnebors', models.CharField(max_length=999)),
            ],
        ),
    ]
