# Generated by Django 2.1.3 on 2018-11-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsi_midagi', models.CharField(max_length=999)),
                ('loosung', models.CharField(max_length=999)),
            ],
        ),
    ]
