# Generated by Django 2.1.3 on 2018-11-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=999)),
                ('email', models.CharField(max_length=999)),
                ('address', models.CharField(max_length=999)),
            ],
        ),
    ]
