# Generated by Django 2.2.9 on 2020-01-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_delete_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999)),
                ('desc', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=999)),
            ],
        ),
    ]
