# Generated by Django 2.2.9 on 2020-01-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_misc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misc',
            old_name='phone',
            new_name='author',
        ),
        migrations.AddField(
            model_name='misc',
            name='keywords',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
